trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: NodeTool@0
  inputs:
    versionSpec: '18.x'

# FRONTEND
- script: |
    cd frontend
    npm install
    npm test
  displayName: 'Frontend tests'

# BACKEND
- script: |
    cd backend
    npm install
    npm test
  displayName: 'Backend tests'